### ISSUE TITLE
Possibly a mistake in computing Q value in the ipython notebook

### ISSUE THREAD

**Issue by vatula** [wagonhelm/Reinforcement-Learning-Introduction#1]
I am referring to the Taxi domain and this solution
```python
for episode in range(1,1001):
    done = False
    G, reward = 0,0
    state = env.reset()
    while done != True:
            action = np.argmax(Q[state]) #1
            state2, reward, done, info = env.step(action) #2
            Q[state,action] += alpha * (reward + np.max(Q[state2]) - Q[state,action]) #3
...
```
It seems that on #2, variable `reward` refers to the reward one gets for being in `state2` (according to https://gym.openai.com/docs/). However, Q value update rule in Sutton and wiki mentions the reward at the current state, `state`. I see that in an episode initialisation step there's a `reward` variable initialised but overwritten immediately by #2.

Could it be that an intention was to update current reward after #3 with a reward on getting to `state2`? As in
```python
for episode in range(1,1001):
    done = False
    G, reward = 0,0
    state = env.reset()
    while done != True:
            action = np.argmax(Q[state]) #1
            state2, reward2, done, info = env.step(action) #2
            Q[state,action] += alpha * (reward + np.max(Q[state2]) - Q[state,action]) #3
            reward = reward2
```

**Comment by dagostal** [comment]
Thanks for the code! But wouldn't the total reward/ q values converge? Also where is the agent exploring

**Comment by wagonhelm** [comment]
@vatula I'm quite certain the implementation is correct, the idea is that reward is the reward received from the action taken in state, not state2.  You do not receive any reward when initializing your initial state (you haven't done anything yet!), rewards are the result of taking a particular action in a given state.  This is dynamic programming and in a sense behaves recursively, you are always updating the action value of your current state and action taken based upon the reward you received when transitioning from state to state2 and the best action value from state2.  Have you tried implementing your suggestion?  Hopefully this makes sense!

@dagostal yes the values will converge, the beauty the environment is that you receive a negative reward each step you don't finish the required tasks.  You have four buttons to press, you press the first one and you get a zap, when you go to hit a button again which one do you press?
