### ISSUE TITLE
incorrect dimensions for Q matrix

### ISSUE THREAD

**Issue by shervn-r** [wagonhelm/Reinforcement-Learning-Introduction#2]
in `frozenIce.ipynb` file Q matrix dimensions defined incorrectly as `Q = np.zeros([n_states, n_states])`, instead it should be `Q = np.zeros([n_states, n_actions])`.

**Comment by wagonhelm** [comment]
Nice catch, it still "sort-of" works because any action above 3 never got evaluated. Fixed
